shared:
    image: node:12

jobs:
    A:
        steps:
            - echo: echo test
            - meta-set: meta set build.version A
            - meta-get: meta get build.version
        requires: [~commit, ~pr]

    # B will run after A
    B:
        steps:
            - echo: echo test
            - meta: meta get build.version
        requires: [A]
    # B will run after A
    B2:
        steps:
            - echo: echo test
            - meta: meta set build.version
            - sleep: sleep 20
        requires: [A]

    # C will run after B
    C:
        steps:
            - echo: echo test
        requires: [B, B2]
